sudo: false

language: scala

jdk:
  - oraclejdk8

env:
  - "IDEA_VERSION=2016.1.3;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/25793/php-145.970.40.zip"
  - "IDEA_VERSION=2016.2.5;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/27859/php-162.1628.23.zip"
  - "IDEA_VERSION=2016.3.3;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/31161/php-163.10504.2.zip"
  - "IDEA_VERSION=171-SNAPSHOT;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/31870/php-171.2455.9.zip"

install:
   - sbt -DIDEA_VERSION=$IDEA_VERSION -DPHP_PLUGIN_URL=$PHP_PLUGIN_URL test

script:
   - sbt -DIDEA_VERSION=$IDEA_VERSION -DPHP_PLUGIN_URL=$PHP_PLUGIN_URL "; pluginPack ; pluginCompress ; pluginProguard"

matrix:
  allow_failures:
    # allow failure for EAP
    - env: "IDEA_VERSION=171-SNAPSHOT;PHP_PLUGIN_URL=https://plugins.jetbrains.com/files/6610/31870/php-171.2455.9.zip"
